// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelNS;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(ModelData))]
    partial class ModelDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataClass.Bestilling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Bemærkninger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VareId");

                    b.ToTable("Bestillinger");
                });

            modelBuilder.Entity("DataClass.Vare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pris")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Varer");
                });

            modelBuilder.Entity("DataClass.Bestilling", b =>
                {
                    b.HasOne("DataClass.Vare", "Vare")
                        .WithMany("Bestillinger")
                        .HasForeignKey("VareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vare");
                });

            modelBuilder.Entity("DataClass.Vare", b =>
                {
                    b.Navigation("Bestillinger");
                });
#pragma warning restore 612, 618
        }
    }
}
